from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from .models import User
from .serializers import UserSerializer, UserCreateSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    ViewSet for User model.
    
    Provides CRUD operations:
    - GET /api/users/ - List all users
    - GET /api/users/{id}/ - Get specific user
    - POST /api/users/ - Create new user
    - PUT /api/users/{id}/ - Update user (full)
    - PATCH /api/users/{id}/ - Update user (partial)
    - DELETE /api/users/{id}/ - Delete user
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [AllowAny]  # Change to IsAuthenticated for production
    
    def get_serializer_class(self):
        """
        Use UserCreateSerializer for creation, UserSerializer for other operations.
        """
        if self.action == 'create':
            return UserCreateSerializer
        return UserSerializer
    
    def create(self, request, *args, **kwargs):
        """
        Create a new user.
        If name is not provided, it will be auto-generated by the model.
        """
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        
        # Return the created user with UserSerializer (excludes password)
        response_serializer = UserSerializer(user)
        return Response(response_serializer.data, status=status.HTTP_201_CREATED)
    
    @action(detail=False, methods=['get'])
    def me(self, request):
        """
        Custom endpoint: GET /api/users/me/
        Returns the current authenticated user.
        """
        # For now, returns first user (in production, use request.user)
        if request.user and request.user.is_authenticated:
            serializer = self.get_serializer(request.user)
            return Response(serializer.data)
        return Response(
            {"detail": "Authentication required"},
            status=status.HTTP_401_UNAUTHORIZED
        )
    
    @action(detail=True, methods=['patch'])
    def update_profile(self, request, pk=None):
        """
        Custom endpoint: PATCH /api/users/{id}/update_profile/
        Update user profile (partial update).
        """
        user = self.get_object()
        serializer = self.get_serializer(user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
